# Rakefile for File::Tail      -*- ruby -*-

require 'rake/gempackagetask'
require 'rbconfig'

include Config

PKG_NAME = 'term-ansicolor'
PKG_VERSION = File.read('VERSION').chomp
PKG_FILES = Dir.glob("**/*").delete_if { |item|
    item.include?("CVS") or item.include?("pkg")
}

desc "Installing library"
task :install  do
    libdir = CONFIG["sitelibdir"]
    dest = File.join(libdir, 'term')
    install('lib/term/ansicolor.rb', dest)
end

spec = Gem::Specification.new do |s|

    #### Basic information.

    s.name = 'term-ansicolor'
    s.version = PKG_VERSION
    s.summary = "Ruby library that colors strings using ANSI escape sequences"
    s.description = ""

    #### Dependencies and requirements.

    #s.add_dependency('log4r', '> 1.0.4')
    #s.requirements << ""

    s.files = PKG_FILES

    #### C code extensions.

    #s.extensions << "ext/extconf.rb"

    #### Load-time details: library and application (you will need one or both).

    s.require_path = 'lib'                         # Use these for libraries.
    #s.autorequire = 'term/ansicolor'

    #s.bindir = "bin"                               # Use these for applications.
    #s.executables = ["bla.rb"]
    #s.default_executable = "bla.rb"

    #### Documentation and testing.

    s.has_rdoc = false
    #s.has_rdoc = true
    #s.extra_rdoc_files = rd.rdoc_files.reject { |fn| fn =~ /\.rb$/ }.to_a
    #s.rdoc_options <<
    #  '--title' <<  'Rake -- Ruby Make' <<
    #  '--main' << 'README' <<
    #  '--line-numbers'

    #### Author and project details.

    s.author = "Florian Frank"
    s.email = "flori@ping.de"
    s.homepage = "http://term-ansicolor.rubyforge.org"
    s.rubyforge_project = "term-ansicolor"
end

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_tar = true
    pkg.package_files += PKG_FILES
end
    # vim: set et sw=4 ts=4:
